export const defaultDadlyCarousel = {
  theme: 'viral baby questions dads are afraid to ask',
  slides: [
    {
      type: 'hook',
      eyebrow: 'Every dad has asked this',
      headline: "Questions you Google\nat 3am so your\npartner *doesn't* see.",
      subtext: "4 things dads panic about, answered without the spiral.",
      handle: 'pagefordads',
      roleTag: 'FOR DADS',
    },
    {
      type: 'lesson',
      lessonLabel: 'Q 01 · CRYING',
      ghostNumber: '01',
      headline: "Is it *normal* for a baby to cry this much?",
      body: "Yes, and it peaks at 6 weeks before dropping sharply. **A healthy newborn can cry 2 to 3 hours a day and that is completely normal.** It is not a sign you are doing it wrong. It is the only language they have right now.",
      handle: 'pagefordads',
    },
    {
      type: 'lesson',
      lessonLabel: 'Q 02 · BREATHING',
      ghostNumber: '02',
      headline: "Why does my baby *stop breathing* for a second?",
      body: "Newborns have periodic breathing: normal pauses of 5 to 10 seconds between breaths. **Their brainstem is still calibrating. This is not sleep apnoea.** Call a doctor only if the pause lasts 20 or more seconds or the lips turn blue.",
      handle: 'pagefordads',
    },
    {
      type: 'lesson',
      lessonLabel: 'Q 03 · SOFT SPOT',
      ghostNumber: '03',
      headline: "Can I hurt my baby by *touching* the soft spot?",
      body: "No. The fontanelle feels soft but it is protected by a tough membrane. Normal touching, bathing, and holding will not harm it. **It is safe to wash and touch gently.** Worry only if it is bulging when baby is calm and upright.",
      handle: 'pagefordads',
    },
    {
      type: 'lesson',
      lessonLabel: 'Q 04 · POOP',
      ghostNumber: '04',
      headline: "Why is my baby's poop *that* colour?",
      body: "Yellow, green, seedy, or mustard are all normal for newborns. **The first few days: black tar (meconium). After that: yellow-green, then yellow and seedy if breastfed.** Only red, white, or black after day 4 needs a doctor call.",
      handle: 'pagefordads',
    },
    {
      type: 'cta',
      eyebrow: 'No more 3am spirals',
      headline: 'Get the answer\nin 10 seconds.',
      subtitle: "Dadly gives new dads instant, calm answers to every question they are afraid to ask. Available 24/7.",
      pillars: [
        'Ask anything about baby or pregnancy',
        'Tells you: totally normal, watch it, or call now',
        'Weekly guides matched to your baby\'s actual age',
        'Decodes medical reports in plain English',
        'Built for dads, not just mums',
      ],
      handle: 'pagefordads',
    },
  ],
}
