export const defaultDadlyCarousel = {
  theme: 'new dad survival guide',
  slides: [
    {
      type: 'hook',
      eyebrow: '↓ Every new dad needs this',
      headline: "It's 3am.\nBaby won't stop crying.\n*Nobody* told you this.",
      subtext: "5 things every new dad needs to know — that doctors forget to mention.",
      handle: 'pagefordads',
      roleTag: 'FOR DADS',
    },
    {
      type: 'lesson',
      lessonLabel: 'Tip 01 · Crying',
      ghostNumber: '01',
      headline: 'Crying *peaks* at 6 weeks. Then it drops.',
      body: "Your baby isn't broken. **Crying is the only language newborns have.** It peaks around 6 weeks then drops sharply — even when nothing changes. You're not doing it wrong.",
      handle: 'pagefordads',
    },
    {
      type: 'lesson',
      lessonLabel: 'Tip 02 · Sleep',
      ghostNumber: '02',
      headline: 'There is *no* sleep schedule before 3 months.',
      body: "Newborns can't tell day from night — their circadian rhythm isn't developed yet. **Stop trying to 'fix' the sleep. Start surviving it in shifts.** It resets naturally around 12–16 weeks.",
      handle: 'pagefordads',
    },
    {
      type: 'lesson',
      lessonLabel: 'Tip 03 · Feeding',
      ghostNumber: '03',
      headline: 'Fed is *always* the right answer.',
      body: "Breast, formula, combination — **all three produce healthy, thriving babies.** The pressure on new parents to 'choose correctly' causes more harm than any feeding method. Do what works for your family.",
      handle: 'pagefordads',
    },
    {
      type: 'lesson',
      lessonLabel: 'Tip 04 · When to worry',
      ghostNumber: '04',
      headline: 'Most scares are *normal*. Some aren\'t.',
      body: "**Trust your gut — but know the red flags:** fever above 38°C in under 3 months, blue lips, difficulty breathing, or no wet nappies for 8+ hours. Everything else? Usually fine. Dadly tells you which is which.",
      handle: 'pagefordads',
    },
    {
      type: 'cta',
      eyebrow: 'Built for dads like you',
      headline: 'Get answers\nat 3am.',
      subtitle: 'Dadly gives new and expecting dads instant, clear answers — without the panic spiral.',
      pillars: [
        'Smart chat for baby & pregnancy questions',
        'Weekly guides by your baby\'s actual age',
        'Decodes medical reports in plain English',
        'Tells you: normal, wait, or call the doctor',
        'Available 24/7 — even at 3am',
      ],
      handle: 'pagefordads',
    },
  ],
}
